env: "local"
postgres:
  host: "postgres"
  port: 5432
  user_name: ""
  user_pass: ""
  db_name: tg-queue
amqp:
  host: "rabbitmq"
  port: 5672
  user_name: ""
  user_pass: ""
  queue: response_yt_q_v2
  exchange: enricher-out
  routing_key: test-key
otlp_config:
  host: "jaeger"
  port: 4317
  service_name: "tg-enricher"